version: '2.1'

services:
  scylla:
    image: scylladb/scylla:2.1.1
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
  kairosdb: 
    build: .
    environment:
      - KAIROSDB_SERVICE_DATASTORE=org.kairosdb.datastore.cassandra.CassandraModule
      - KAIROSDB_DATASTORE_CASSANDRA_CQL_HOST_LIST=scylla
    ports: 
      - "8080:8080" 
    depends_on:
      scylla:
        condition: service_healthy
